version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=Abc.2024
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "Abc.2024"]
    restart: always
    networks:
      - app_network
    ports:
      - "6379:6379"

  gameoflife:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5003:443"  
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_CONNECTION=redis:6379,password=Abc@2024,abortConnect=false
    restart: always
    networks:
      - app_network
